name: e2e tests

on:
  push:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run e2e tests
        run: npx playwright test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retentionDays: 30
